name: Documentation

on: push

jobs:
    deploy:
        name: Deploy to Github pages
        runs-on: ubuntu-latest
        container: kviktor58/mosze2:latest
        steps:
            - uses: actions/checkout@master
              
            - name: Generate docs
              run: doxygen Doxyconf
			- name: Make doc
              run: make documentation

            - name: Push git subdir branch
              uses: s0/git-publish-subdir-action@v2.4.0

              env:
                REPO: self
                BRANCH: documentation
                FOLDER: DOCS/html
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}