name: inOutTest

on:
 push

jobs:
 build:
  runs-on: ubuntu-latest
  container: kviktor58/mosze:latest
  steps:
   - uses: actions/checkout@v2 
   - run: apt update
   - run: apt-get install cmake -y
   - run: apt install clang -y
   - run: make build
   - run: chmod +x ./run_test.sh
   - run: ./run_test.sh
   - run: diff ./out_res.txt ./units/out_ok.txt
   - run: diff ./out_res2.txt ./units/out_ok2.txt
   - run: cmake ./unitTest/CMakeLists.txt
   - run: make
   - run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a
   - run: ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
   - run: make UnitTest