name: Threeunits

on:
 push

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - run: g++  -std=c++17 *.cpp -o b
   - run: chmod +x ./run_test.sh
   - run: ./run_test.sh
   - run: diff ./out_res.txt ./units/out_ok.txt