name: Threeunits

on:
 push

jobs:
 build:
  runs-on: ubuntu-latest
  container: kviktor58/mosze:latest
  steps:
   - uses: actions/checkout@v2 
   - run: apt-get install clang-7 clang-tools-7 clang-7-doc libclang-common-7-dev libclang-7-dev libclang1-7 clang-format-7 python-clang-7 
   - run: make build
   - run: chmod +x ./run_test.sh
   - run: ./run_test.sh
   - run: diff ./out_res.txt ./units/out_ok.txt
   - run: diff ./out_res2.txt ./units/out_ok2.txt