name: Threeunits

on:
 push

jobs:
 build:
  runs-on: ubuntu-latest
  container: kviktor58/mosze:latest
steps:
      - uses: actions/checkout@v2
      - name: Build with make and cmake
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make
      - name: Using references to gtest
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Unit tests
        run: make UnitTest