name: unitTest

on:
 push

jobs:
 build:
  runs-on: ubuntu-latest
  container: kviktor58/mosze:latest
  steps:
   - uses: actions/checkout@v2 
   - run: apt update
   - run: cmake ./unitTest/CMakeLists.txt
   - run: make
   - run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a
   - run: ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
   - run: make unitTest